language: c

sudo: false
notifications:
  email: false

branches:
  only:
    - master

env:
  - OS_PACKAGES="build-essentials zlib1g-dev gcc checkinstall"

compiler:
  - gcc

python:
  - 3.5

install:
  - sudo pip install -r dev_requirements.txt
  - sudo apt-get install -y $OS_PACKAGES
  - make -f libxlsxwriter/Makefile
  - sudo checkinstall make -f libxlsxwriter/Makefile install
  - python setup.py build_ext bdist_wheel

script:
  - echo "No tests for now, only build phase"
